title: MSXVR Documentation
description: >-
  MSXVR Documentation
url: ""
github_username:  msxrv

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  documents:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
    values:
      layout: "default"  
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "documents"    

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: /assets/css
  style: compressed

  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
