title: MSXVR Documentation
description: >-
  MSXVR Documentation
url: ""
github_username:  msxrv

collections:
  documents:
    output: true

defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "documents"
  - scope:
      path: "" 
    values:
      layout: "default"      

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
