name: CI
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Create Dist folder
        run: mkdir dist

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown+pipe_tables  -s _documents/cheatsheet.md -o dist/cheatsheet.pdf --metadata title="Cheatsheet"

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown+pipe_tables  -s _documents/atajos_teclado.md -o dist/atajos.pdf --metadata title="Atajos de teclado"

      # - uses: docker://pandoc/latex:2.9
      #   with:
      #     args:  -s _documents/manual_programacion.md --toc -o dist/manual_programacion.pdf --metadata title="Manual de Usuario"

      - uses: docker://pandoc/core:2.9
        with:
          args:  -s _documents/manual_programacion.md --toc -o dist/manual_programacion.epub --metadata title="Manual de Usuario"

      - name: Deploy to Dropbox
        uses: aTable/deploy-to-dropbox@v1.0.7
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path:  dist/*      