name: CI
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Main repo
        uses: actions/checkout@v2
        with:
          path: ./site

      - name: Checkout Documents repo
        uses: actions/checkout@master
        with:
          name: msxrv/documentos
          path: ./documents

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown+pipe_tables  -s site/_documents/cheatsheet.md -o documents/cheatsheet.pdf --metadata title="Cheatsheet"

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown+pipe_tables  -s site/_documents/atajos_teclado.md -o documents/atajos.pdf --metadata title="Atajos de teclado"

      # - uses: docker://pandoc/latex:2.9
      #   with:
      #     args:  -s _documents/manual_programacion.md --toc -o dist/manual_programacion.pdf --metadata title="Manual de Usuario"

      - uses: docker://pandoc/core:2.9
        with:
          args:  -s site/_documents/manual_programacion.md --toc -o documents/manual_programacion.epub --metadata title="Manual de Usuario"

      - name: commit
        run: |
          cd ./documents
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Publish new documents"
          git push           